# Generated by Django 5.2.6 on 2025-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="map_link",
        ),
        migrations.AddField(
            model_name="institution",
            name="gis_map_link",
            field=models.URLField(
                default="https://yandex.ru/maps/-/CLeCaX4y",
                max_length=500,
                verbose_name="Ссылка на 2GIS",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="yandex_map_link",
            field=models.URLField(
                default="https://yandex.ru/maps/-/CLeCaX4y",
                max_length=500,
                verbose_name="Ссылка на Yandex Maps",
            ),
            preserve_default=False,
        ),
    ]
