# Generated by Django 5.2.6 on 2025-09-23 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0002_remove_institution_map_link_institution_gis_map_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="confidence",
            field=models.FloatField(
                help_text="Значение от 0.0 до 1.0",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Уверенность модели",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Положительный"),
                    ("negative", "Отрицательный"),
                    ("spam", "Спам"),
                ],
                max_length=10,
                null=True,
                verbose_name="Тональность отзыва",
            ),
        ),
    ]
