# Generated by Django 5.2.6 on 2025-09-23 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_confidence_alter_review_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewed_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 23, 17, 8, 6, 116023),
                verbose_name="Дата написания отзыва",
            ),
            preserve_default=False,
        ),
    ]
