# Generated by Django 5.2.6 on 2025-09-28 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_review_reviewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 9, 28, 19, 28, 52, 707218),
                verbose_name="Дата мероприятия",
            ),
            preserve_default=False,
        ),
    ]
