# Generated by Django 5.2.6 on 2025-10-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("positive", "Положительный"),
                    ("negative", "Отрицательный"),
                    ("neutral", "Нейтральный"),
                ],
                max_length=64,
                null=True,
                verbose_name="Тональность отзыва",
            ),
        ),
    ]
