# Generated by Django 5.2.6 on 2025-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_alter_review_sentiment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="keywords",
        ),
        migrations.AddField(
            model_name="review",
            name="negative_aspects",
            field=models.JSONField(
                default=list,
                help_text="Список аспектов в формате JSON",
                verbose_name="Негативные аспекты отзыва",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="positive_aspects",
            field=models.JSONField(
                default=list,
                help_text="Список аспектов в формате JSON",
                verbose_name="Позитивные аспекты отзыва",
            ),
        ),
    ]
