# Generated by Django 5.2.6 on 2025-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_remove_review_keywords_review_negative_aspects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="ok_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на Одноклассники"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="otzovik_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на Отзовик"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="telegram_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на Telegram"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="vk_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на ВК"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="gis_map_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на 2GIS"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="yandex_map_link",
            field=models.URLField(
                max_length=500, null=True, verbose_name="Ссылка на Yandex Maps"
            ),
        ),
    ]
