# Generated by Django 5.2.6 on 2026-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_institution_ok_link_institution_otzovik_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="source",
            field=models.CharField(
                default="2GIS", max_length=64, verbose_name="Источник отзыва"
            ),
            preserve_default=False,
        ),
    ]
