# Generated by Django 5.2.6 on 2026-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_review_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="required_actions",
            field=models.JSONField(
                default=list,
                help_text="Список дейсвтий в формате JSON",
                verbose_name="Предлагаемые в отзыве действия",
            ),
        ),
    ]
