# Generated by Django 5.2.6 on 2026-03-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_review_required_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedActionWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Слово/Фраза"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово предлагаемого действия",
                "verbose_name_plural": "Мешок слов предлагаемых действий",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="potential_actions",
            field=models.JSONField(
                default=list,
                help_text="Список потенциальных действий в формате JSON",
                verbose_name="Потенциальные действия из отзыва",
            ),
        ),
    ]
