# Generated by Django 5.2.6 on 2026-05-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_suggestedactionword_review_potential_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_rent",
            field=models.BooleanField(default=False, verbose_name="Аренда"),
        ),
    ]
